In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_excel("/content/sample_data/Online Retail.xlsx")

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [3]:
print("Shape Before Cleaning:")
print(df.shape)

Shape Before Cleaning:
(541909, 8)

In [5]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [4]:
df = df.dropna(subset=["CustomerID"])

print(df.shape)

(406829, 8)

In [7]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 5225

In [8]:
df = df.drop_duplicates()

print(df.shape)

(401604, 8)

In [9]:
cancelled = df[df["InvoiceNo"].astype(str).str.startswith("C")]

cancelled.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

In [10]:
print("Cancelled Orders:", cancelled.shape[0])

Cancelled Orders: 8872

In [11]:
df = df[~df["InvoiceNo"].astype(str).str.startswith("C")]

print(df.shape)

(392732, 8)

In [12]:
df["Quantity"].describe()

count    392732.000000
mean         13.153718
std         181.588420
min           1.000000
25%           2.000000
50%           6.000000
75%          12.000000
max       80995.000000
Name: Quantity, dtype: float64

In [13]:
df = df[df["UnitPrice"] > 0]

print(df.shape)

(392692, 8)

In [14]:
df["CustomerID"] = df["CustomerID"].astype(int)
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              int64
Country                object
dtype: object

In [15]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

df["InvoiceDate"].head()

0   2010-12-01 08:26:00
1   2010-12-01 08:26:00
2   2010-12-01 08:26:00
3   2010-12-01 08:26:00
4   2010-12-01 08:26:00
Name: InvoiceDate, dtype: datetime64[ns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392692 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    392692 non-null  object
 1   StockCode    392692 non-null  object
 2   Description  392692 non-null  object
 3   Quantity     392692 non-null  int64
 4   InvoiceDate  392692 non-null  datetime64[ns]
 5   UnitPrice    392692 non-null  float64
 6   CustomerID   392692 non-null  int64
 7   Country      392692 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 27.0+ MB

In [17]:
print("Final Shape:")
print(df.shape)

Final Shape:
(392692, 8)

In [18]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [20]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [19]:
print(df.duplicated().sum())

0

In [21]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,392692.000000,392692,392692.000000,392692.000000
mean,13.119702,2011-07-10 19:13:07.771892480,3.125914,15287.843865
min,1.000000,2010-12-01 08:26:00,0.001000,12346.000000
25%,2.000000,2011-04-07 11:12:00,1.250000,13955.000000
50%,6.000000,2011-07-31 12:02:00,1.950000,15150.000000
75%,12.000000,2011-10-20 12:53:00,3.750000,16791.000000
max,80995.000000,2011-12-09 12:50:00,8142.750000,18287.000000
std,180.492832,NaN,22.241836,1713.539549

In [22]:
df.sample(10, random_state=42)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
476492,577022,82494L,WOODEN FRAME ANTIQUE WHITE,6,2011-11-17 12:42:00,2.95,13668,United Kingdom
224781,556576,22139,RETROSPOT TEA SET CERAMIC 11 PC,2,2011-06-13 13:55:00,4.95,14606,United Kingdom
285767,561923,21123,SET/10 IVORY POLKADOT PARTY CANDLES,24,2011-08-01 12:16:00,1.25,14112,United Kingdom
428995,573511,22417,PACK OF 60 SPACEBOY CAKE CASES,24,2011-10-31 12:25:00,0.55,12347,Iceland
238045,557893,23171,REGENCY TEA PLATE GREEN,12,2011-06-23 14:12:00,1.65,15228,United Kingdom
108174,545515,22715,CARD WEDDING DAY,12,2011-03-03 12:06:00,0.42,12727,France
138794,548212,22857,ASSORTED EASTER GIFT TAGS,12,2011-03-30 09:12:00,0.85,12456,Switzerland
107320,545428,22423,REGENCY CAKESTAND 3 TIER,4,2011-03-02 14:43:00,12.75,14239,United Kingdom
491767,578074,23491,VINTAGE JINGLE BELLS HEART,5,2011-11-22 16:06:00,8.25,17590,United Kingdom
432620,573876,21917,SET 12 KIDS WHITE CHALK STICKS,2,2011-11-01 12:48:00,0.42,16360,United Kingdom

In [24]:
df.to_csv("/content/sample_data/cleaned_data.csv", index=False)

print("Cleaned Dataset Saved Successfully!")

Cleaned Dataset Saved Successfully!