# AI-Powered Customer Segmentation

## Notebook 04 : RFM Feature Engineering

### Objectives

- Create Recency
- Create Frequency
- Create Monetary
- Build Customer Level Dataset
- Save RFM Dataset

In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns",None)

In [3]:
df = pd.read_csv("/content/sample_data/eda_ready_data.csv")

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Month,Weekday
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010-12,Wednesday
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010-12,Wednesday
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010-12,Wednesday
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010-12,Wednesday
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010-12,Wednesday

In [4]:
print(df.shape)

df.info()

(392692, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392692 entries, 0 to 392691
Data columns (total 11 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    392692 non-null  int64
 1   StockCode    392692 non-null  object
 2   Description  392692 non-null  object
 3   Quantity     392692 non-null  int64
 4   InvoiceDate  392692 non-null  datetime64[ns]
 5   UnitPrice    392692 non-null  float64
 6   CustomerID   392692 non-null  int64
 7   Country      392692 non-null  object
 8   TotalPrice   392692 non-null  float64
 9   Month        392692 non-null  object
 10  Weekday      392692 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(3), object(5)
memory usage: 33.0+ MB

In [5]:
print("Minimum Date :",df["InvoiceDate"].min())

print("Maximum Date :",df["InvoiceDate"].max())

Minimum Date : 2010-12-01 08:26:00
Maximum Date : 2011-12-09 12:50:00

In [6]:
snapshot_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)

print(snapshot_date)

2011-12-10 12:50:00

In [7]:
recency = (df.groupby("CustomerID")["InvoiceDate"].max())

recency = (snapshot_date-recency).dt.days
recency.head()

CustomerID
12346    326
12347      2
12348     75
12349     19
12350    310
Name: InvoiceDate, dtype: int64

In [8]:
frequency = (df.groupby("CustomerID")["InvoiceNo"].nunique())

frequency.head()

CustomerID
12346    1
12347    7
12348    4
12349    1
12350    1
Name: InvoiceNo, dtype: int64

In [9]:
monetary = (df.groupby("CustomerID")["TotalPrice"].sum())

monetary.head()

CustomerID
12346    77183.60
12347     4310.00
12348     1797.24
12349     1757.55
12350      334.40
Name: TotalPrice, dtype: float64

In [10]:
rfm = pd.DataFrame({
    "Recency":recency,
    "Frequency":frequency,
    "Monetary":monetary
})

rfm.head()

            Recency  Frequency  Monetary
CustomerID
12346           326          1  77183.60
12347             2          7   4310.00
12348            75          4   1797.24
12349            19          1   1757.55
12350           310          1    334.40

In [11]:
rfm = rfm.reset_index()
rfm.head()

   CustomerID  Recency  Frequency  Monetary
0       12346      326          1  77183.60
1       12347        2          7   4310.00
2       12348       75          4   1797.24
3       12349       19          1   1757.55
4       12350      310          1    334.40

In [12]:
print(rfm.shape)

(4338, 4)

In [13]:
rfm.isnull().sum()

CustomerID    0
Recency       0
Frequency     0
Monetary      0
dtype: int64

In [14]:
rfm.describe()

         CustomerID      Recency    Frequency       Monetary
count   4338.000000  4338.000000  4338.000000    4338.000000
mean   15300.408022    92.536422     4.272015    2048.688081
std     1721.808492   100.014169     7.697998    8985.230220
min    12346.000000     1.000000     1.000000       3.750000
25%    13813.250000    18.000000     1.000000     306.482500
50%    15299.500000    51.000000     2.000000     668.570000
75%    16778.750000   142.000000     5.000000    1660.597500
max    18287.000000   374.000000   209.000000  280206.020000

In [15]:
rfm.sort_values("Monetary",ascending=False).head(10)

      CustomerID  Recency  Frequency   Monetary
1689       14646        2         73  280206.02
4201       18102        1         60  259657.30
3728       17450        8         46  194390.79
3008       16446        1          2  168472.50
1879       14911        1        201  143711.17
55         12415       24         21  124914.53
1333       14156       10         55  117210.08
3771       17511        3         31   91062.38
2702       16029       39         63   80850.84
0          12346      326          1   77183.60

In [16]:
rfm.sort_values("Frequency",ascending=False).head(10)

      CustomerID  Recency  Frequency   Monetary
326        12748        1        209   33053.19
1879       14911        1        201  143711.17
4010       17841        2        124   40519.84
562        13089        3         97   58762.08
1661       14606        1         93   12076.15
2176       15311        1         91   60632.75
481        12971        4         86   11189.91
1689       14646        2         73  280206.02
2702       16029       39         63   80850.84
795        13408        2         62   28117.04

In [17]:
rfm.sort_values("Recency").head(10)

      CustomerID  Recency  Frequency  Monetary
3662       17364        1         11   4462.68
71         12433        1          7  13375.87
934        13599        1         21   5149.92
892        13536        1          7   3444.39
3366       16933        1          2    563.23
3823       17581        1         25  11025.24
2611       15898        1          5   1383.83
3333       16892        1          5    518.19
3868       17644        1         11   2895.64
2620       15910        1          8   1228.88

In [18]:
rfm.to_csv("/content/sample_data/rfm_data.csv",index=False)

print("RFM Dataset Saved Successfully")

RFM Dataset Saved Successfully

In [19]:
rfm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4338 entries, 0 to 4337
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  4338 non-null   int64
 1   Recency     4338 non-null   int64
 2   Frequency   4338 non-null   int64
 3   Monetary    4338 non-null   float64
dtypes: float64(1), int64(3)
memory usage: 135.7 KB

# Business Insights

### Recency

- Lower Recency means customers purchased more recently.
- Higher Recency indicates inactive customers.

### Frequency

- Higher Frequency customers purchase more often.
- Low Frequency customers are occasional buyers.

### Monetary

- Higher Monetary customers contribute more revenue.
- Lower Monetary customers have lower business value.

### Conclusion

The transaction-level dataset has been successfully transformed into a customer-level RFM dataset.

This dataset is now ready for scaling and K-Means clustering.